### ISSUE TITLE
Looking for contributors ?

### ISSUE THREAD

**Issue by iTrooz** [iTrooz/efiboot-rs#41]
Hey, if I ever get time to do this, would you accept contributions to the `efiboot` tool ? In particular, I'd like to add a way to delete and add new UEFI boot entries. Maybe even get on feature parity with efiboomgr ?

**Comment by iTrooz** [comment]
@vtavernier Hi, I see you are reviewing my PRs right now, so I wanted to take this opportunity to ask you something.

I'd like to fork this repository to continue working on the project from there

My reasons are:
- As much as I love you reviewing my PRs (I'm still relatively new in Rust), I find it a bit annoying to have to wait ~a week each time for my PRs to be merged (This is not in any way a criticism addressed to you, you can do whatever you want with your free time)
- I plan to contribute in the long term to this project, and I'd like have more control over its infrastructure, in the case you don't come around anymore and I find myself with no access to continue working

Forking the project itself is not a big problem, but I'd like to have access to the https://crates.io/efivar crate to be able to update it myself (not really `efiboot`, I plan to change its name to `efivarcli` since its not limited to boot variables stuff).
Plus, I kinda wanted an excuse to talk to you about this, since I think it would be an asshole move to just fork the project and move on without talking to you about it

So.. would you be okay with my forking the project, and would you be okay with giving me access to publish the efivar crate ?

**Comment by vtavernier** [comment]
Hello @iTrooz 

Thanks for being upfront about this. I've been busy recently (and away for the past two weeks), hence the delay in reviewing PRs. I haven't caught up yet but looking at the recent code you pushed, I think it makes sense you could become the maintainer for this project.

Since I'm available to figure this out, here's my proposal:
- I add you as owner of efiboot and efivar crates on crates.io (there's no point in me keeping access to only one of those)
- I transfer this repository from my user to yours on Github (in the Settings > Transfer repository option)

I think the transfer option is preferable to a fork, since it'll automatically redirect users to the new home for the project, as well as keep all issues and open pull requests. What do you think?

**Comment by iTrooz** [comment]
I think that would be great to keep issues and PRs, yeah !

> I add you as owner of efiboot and efivar crates on crates.io (there's no point in me keeping access to only one of those)

Just to be sure I understand, do you want me to remove your access from the crates once I am an owner ?

**Comment by vtavernier** [comment]
> > I add you as owner of efiboot and efivar crates on crates.io (there's no point in me keeping access to only one of those)
> 
> Just to be sure I understand, do you want me to remove your access from the crates once I am an owner ?

Yes, but if you plan to stop maintaining the crates at some point in the future don't hesitate to reach out to me if you don't find another maintainer to replace you then.

**Comment by iTrooz** [comment]
Okay !

**Comment by vtavernier** [comment]
I've sent you the invites for crates.io on both crates, but on GitHub you'll need to rename your copy of efiboot-rs to something else so I can initiate the transfer

**Comment by iTrooz** [comment]
I've just accepted the crates.io invitations, and I've renamed my fork

**Comment by vtavernier** [comment]
Ok so it turns out you can't transfer a repository to an organization that contains a fork of the repository itself (*iTrooz already has a repository in the vtavernier/efiboot-rs network*).

I think you'd have to delete your fork, then we do the transfer and you can push your (local) branches to the new repository since you'll become an admin of the repository and re-open the PRs (they'll close automatically when deleting the fork I assume). Would that be okay with you?

**Comment by iTrooz** [comment]
Yep ! I just did it, and it indeed closed the PRs

**Comment by vtavernier** [comment]
You should have received the transfer request now!

**Comment by iTrooz** [comment]
I have the repository !

Well.. thanks for everything, don't hesitate to come by in the future ^^

**Comment by vtavernier** [comment]
Sure thing, thanks for taking on the maintenance!
